version: '3.8'


services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
                  # python3 manage.py makemigrations &&
                  # python3 manage.py migrate &&
    

    env_file: ./.env
    image: django_docker
    ports:
      - 8000:8000
    restart: "on-failure"


  nginx: # service name
    build: ./nginx 

# map the machine port 1339 to the container port 80. Any traffic from 1339 externally will be passed to port 80 of the NGINX container. You can access this container viea localhost:1339
    ports:
     - 1339:80 

# static storages provisioned since django does not handle static files in production
    volumes:
      - static_volume:/home/app/microservice/static 

# will only start if web is up and running
    depends_on:
     - web 

# restart service when it fails
    restart: "on-failure" 


volumes:
  # postgres_data:
  static_volume:
  # rabbitmq:
  # rabbitmq_logs: